"""
run_classification_metrics.py
==============================
Compute classification metrics for LLM diagnostic vignette results,
across all languages and all models.

Metrics per model (overall + per category):
    - Accuracy + Wilson 95% CI
    - Balanced accuracy
    - Weighted F1
    - Macro & weighted sensitivity / specificity (one-vs-rest)
    - Cohen's kappa vs clinician consensus (English only)

Outputs per language:
    - classification_metrics.xlsx  (Overall, Anxiety, Mood, Stress, PerClass_* sheets)
    - Confusion matrix PNGs        (per model overall, per model per category,
                                    all models pooled overall + per category)

Folder structure expected:
    results_folder/
        english/
            <model>/
                english/
                    *results.csv
        multi-lingual/
            <model>/
                <language>/
                    *results.csv

Clinician consensus:
    Generated by run_clinician_metrics.py → clinician_consensus.csv
    Must be run first so the consensus file exists.
"""

from pathlib import Path

import pandas as pd
from sklearn.metrics import classification_report

from icd11_utils import (
    sort_models,
    LANGUAGES,
    apply_label_corrections,
    build_label_distribution,
    build_metrics_sheets,
    build_misclassification_tables,
    build_per_class_sheets,
    load_results,
    plot_confusion_matrix,
    print_sheets,
    save_excel,
    plot_confusion_matrix_pct,
    plot_confusion_matrix_pct_fixed
)

# ---------------------------------------------------------------------------
# Configuration — update paths here
# ---------------------------------------------------------------------------
BASE_PATH = Path("/Users/muellv01/Library/CloudStorage/OneDrive-NYULangoneHealth/Projects/ICD11_WHO")
RESULTS_FOLDER = BASE_PATH / "results_Apr26"
FIGURES_FOLDER = RESULTS_FOLDER / "_Figures"
FIGURES_FOLDER.mkdir(exist_ok=True)

# Clinician consensus — generated by run_clinician_metrics.py
# This is the majority-vote consensus from the harmonised clinician ratings.
CLINICIAN_CONSENSUS_FILE = RESULTS_FOLDER / "_results" / "clinicians" / "clinician_consensus.csv"


def load_clinician_consensus(path: Path) -> pd.Series:
    """
    Load the clinician majority-vote consensus from the CSV generated
    by run_clinician_metrics.py.

    Returns a Series indexed by Vignette_ID with the consensus label.
    Vignettes with ties (no majority) are excluded.
    """
    df = pd.read_csv(path, index_col="Vignette_ID")
    # Exclude ties
    df = df[~df["is_tie"]]
    consensus = df["Clinician_Consensus"].str.strip()
    consensus = consensus[consensus != ""]
    return consensus


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
for LANGUAGE in LANGUAGES:
    print(f"\n{'#'*70}")
    print(f"# Language: {LANGUAGE.upper()}")
    print(f"{'#'*70}")

    output_dir = RESULTS_FOLDER / "_results" / LANGUAGE
    output_dir.mkdir(exist_ok=True, parents=True)

    # Discover files
    if LANGUAGE == "english":
        files = sorted(RESULTS_FOLDER.glob("english/*/english/*results.csv"))
    else:
        files = sorted(RESULTS_FOLDER.glob(f"multi-lingual/*/{LANGUAGE}/*results.csv"))
    files = [f for f in files if "results_old" not in str(f)]

    if not files:
        print(f"  WARNING: No result files found for {LANGUAGE}, skipping.")
        continue

    print(f"Found {len(files)} result files:")
    for f in files:
        print(f"  {f}")

    # Load & preprocess
    combined = load_results(files, llm_part_index=-3)
    combined = apply_label_corrections(combined)

    print(f"\nTotal vignettes: {len(combined)}")
    print(f"Models:          {combined['llm'].unique().tolist()}")
    print(f"Categories:      {combined['Category'].unique().tolist()}")

    # Load clinician consensus (English only)
    clinician_consensus = None
    if LANGUAGE == "english":
        if CLINICIAN_CONSENSUS_FILE.exists():
            clinician_consensus = load_clinician_consensus(CLINICIAN_CONSENSUS_FILE)
            print(f"Clinician consensus loaded: {len(clinician_consensus)} vignettes "
                  f"(ties excluded)")

            # Harmonise Vignette_IDs: LLM IDs are often longer versions
            # of the clinician IDs (e.g. "Anxiety Vignette 1A Anxiety Disorder
            # final 12 04 2014" vs "Anxiety Vignette 1A").
            # Truncate LLM IDs to match: for each LLM ID, find the clinician
            # ID it starts with and rename accordingly.
            clinician_ids = sorted(clinician_consensus.index, key=len, reverse=True)
            id_map = {}
            for llm_id in combined.index.unique():
                for clin_id in clinician_ids:
                    if llm_id.startswith(clin_id):
                        id_map[llm_id] = clin_id
                        break
            if id_map:
                combined = combined.rename(index=id_map)
                n_mapped = len(id_map)
                n_overlap = len(set(id_map.values()) & set(clinician_consensus.index))
                print(f"  Vignette ID harmonisation: {n_mapped} LLM IDs mapped, "
                      f"{n_overlap} overlap with consensus")
            else:
                # Check if they already match
                direct_overlap = len(
                    combined.index.unique().intersection(clinician_consensus.index)
                )
                if direct_overlap > 0:
                    print(f"  Vignette IDs already match: {direct_overlap} overlap")
                else:
                    print("  ⚠️  WARNING: No Vignette_ID overlap found between "
                          "LLM results and clinician consensus!")
                    print("     → Kappa will return NaN. Check ID formats.")
        else:
            print(f"  WARNING: Clinician consensus file not found at "
                  f"{CLINICIAN_CONSENSUS_FILE}")
            print(f"  → Run run_clinician_metrics.py first to generate it.")
            print(f"  → Kappa will be computed vs ground truth instead.")

    # Compute metrics
    sheets = build_metrics_sheets(combined, clinician_consensus=clinician_consensus)
    per_class_sheets = build_per_class_sheets(combined)

    # Save Excel
    all_sheets = {**sheets, **per_class_sheets}
    save_excel(all_sheets, output_dir / "classification_metrics.xlsx")
    print_sheets(sheets)

    # -----------------------------------------------------------------------
    # Misclassification frequency tables — English only
    # -----------------------------------------------------------------------
    if LANGUAGE == "english":
        misclass_sheets = build_misclassification_tables(combined)
        save_excel(
            misclass_sheets,
            output_dir / "misclassification_frequencies.xlsx",
            index=False,
        )
        print_sheets(misclass_sheets)

        label_sheets = build_label_distribution(combined)
        save_excel(
            label_sheets,
            output_dir / "label_distribution.xlsx",
            index=False,
        )
        print_sheets(label_sheets)

    # -----------------------------------------------------------------------
    # Confusion matrices — per model
    # -----------------------------------------------------------------------
    for llm in sort_models(combined["llm"].unique().tolist()):
        group = combined[combined["llm"] == llm]
        y_true = group["Ground_Truth_Label"].values
        y_pred = group["Predicted_Label"].values
        all_labels = sorted(set(y_true) | set(y_pred))

        # Overall
        plot_confusion_matrix(
            y_true, y_pred,
            labels=all_labels,
            title=f"Confusion Matrix — {llm} (all vignettes, {LANGUAGE})",
            save_path=output_dir / f"cm_overall_{llm}.png",
        )

        # Per category
        for cat, cat_group in group.groupby("Category"):
            y_true_cat = cat_group["Ground_Truth_Label"].values
            y_pred_cat = cat_group["Predicted_Label"].values
            cat_labels = sorted(set(y_true_cat) | set(y_pred_cat))
            plot_confusion_matrix(
                y_true_cat, y_pred_cat,
                labels=cat_labels,
                title=f"Confusion Matrix — {llm} / {cat} ({LANGUAGE})",
                save_path=output_dir / f"cm_{cat}_{llm}.png", category=cat, language=LANGUAGE
            )

        print(f"\n{'='*60}\nModel: {llm}\n{'='*60}")
        print(classification_report(y_true, y_pred, labels=all_labels, zero_division=0))

    # -----------------------------------------------------------------------
    # Confusion matrices — all models pooled
    # -----------------------------------------------------------------------
    y_true_all = combined["Ground_Truth_Label"].values
    y_pred_all = combined["Predicted_Label"].values
    all_labels_agg = sorted(set(y_true_all) | set(y_pred_all))

    plot_confusion_matrix(
        y_true_all, y_pred_all,
        labels=all_labels_agg,
        title=f"Confusion Matrix — All Models Pooled ({LANGUAGE})",
        save_path=output_dir / "cm_overall_ALL_MODELS.png",
    )

    for cat, cat_group in combined.groupby("Category"):
        y_true_cat = cat_group["Ground_Truth_Label"].values
        y_pred_cat = cat_group["Predicted_Label"].values
        cat_labels = sorted(set(y_true_cat) | set(y_pred_cat))
        plot_confusion_matrix(
            y_true_cat, y_pred_cat,
            labels=cat_labels,
            title=f"Confusion Matrix — All Models Pooled — {cat}",
            save_path=output_dir / f"cm_{cat}_ALL_MODELS.png", category=cat, language=LANGUAGE
        )
        plot_confusion_matrix_pct(
            y_true_cat, y_pred_cat,
            labels=cat_labels,
            title=f"Confusion Matrix — All Models Pooled — {cat}",
            save_path=output_dir / f"cm_{cat}_ALL_MODELS_percentage.png", category=cat, language=LANGUAGE
        )
        plot_confusion_matrix_pct_fixed(
            y_true_cat, y_pred_cat,
            labels=cat_labels,
            title=f"{cat}",
            save_path=output_dir / f"cm_{cat}_ALL_MODELS_percentage_fixed.png", category=cat, language=LANGUAGE
        )

    print(f"\nAll outputs saved to {output_dir}/")