import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import TextStreamer

model_name = "syzymon/long_llama_code_7b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             torch_dtype=torch.float16, 
                                             trust_remote_code=True,
                                             device_map='auto',
                                             mem_attention_grouping=(1, 2048))


model.eval()

streamer = TextStreamer(tokenizer)
prompt = """
[INST]\n
Describe and summarize the below Social Anxiety Disorder: 
Q5  Social Anxiety Disorder

Essential (Required) Features: Marked and excessive fear or anxiety that occurs consistently in one or more social situations such as social interactions (e.g., having a conversation), being observed (e.g., while eating or drinking), or performing in front of others (e.g., giving a speech). The individual is concerned that he or she will act in a way, or show anxiety symptoms, that will be negatively evaluated by others (i.e., be humiliating, embarrassing, lead to rejection, or be offensive). Relevant social situations are consistently avoided or endured with intense fear or anxiety. The symptoms are not transient; that is, they persist for an extended period of time (e.g., at least several months). The symptoms are sufficiently severe to result in significant distress about experiencing persistent anxiety symptoms or result in significant impairment in personal, family, social, educational, occupational, or other important areas of functioning.

Boundaries with Other Disorders and Normality:Social Anxiety Disorder can be differentiated from normal developmental fears (e.g., a child’s reluctance to interact with unfamiliar people in novel situations) by fear and anxiety reactions that are typically excessive, interfere with functioning, and persist over time (e.g., lasting more than several months). (Boundary with normality) Many individuals experience fear in social situations (e.g., it is common for individuals to experience anxiety about public speaking) or manifest the normal personality trait of shyness. Social Anxiety Disorder should only be considered in cases in which the individual reports social fear, anxiety, and avoidance that are clearly in excess of what is normative for the specific cultural context and result in significant distress or impairment. (Boundary with normality). Individuals with certain medical disorders not classified under Mental and Behavioural Disorders (e.g., Parkinson’s Disease) as well as those with other Mental and Behavioural Disorders (e.g., Schizophrenia) may demonstrate avoidance of social situations because of concerns that others will negatively evaluate their symptoms (e.g., tremor, unusual behaviours). An additional diagnosis of Social Anxiety Disorder should only be assigned if all diagnostic requirements are met taking in to consideration that it is normal for individuals with visible symptoms of a medical disorder to experience some concerns about how others perceive their symptoms. Typically, individuals with medical disorders adapt to concerns related to their manifest symptoms and do not display persistent excessive fear or anxiety in social situations. (Boundary with other Mental and Behavioural Disorders or a Disorder or Disease Classified Elsewhere)
 
Fear or anxiety in Agoraphobia centers on imminent perceived dangerous outcomes (e.g., panic attacks, symptoms of panic, incapacitation, or embarrassing physical symptoms) that are anticipated to occur in multiple situations where obtaining help or escaping might be difficult rather than on concerns that others are negatively evaluating them. Unlike Social Anxiety Disorder, embarrassment in Agoraphobia is secondary to the concerns that escape or obtaining assistance may not be possible should symptoms (e.g., diarrhea in a public place) occur. (Boundary with Agoraphobia)
 
Panic Disorder is characterized by recurrent, unexpected, self-limited panic attacks that occur in multiple situations, whereas when panic attacks occur in Social Anxiety Disorder, they are restricted to social situations. However, Panic Disorder and Social Anxiety Disorder are frequently comorbid and if definitional requirements for both disorders are met both can be diagnosed. (Boundary with Panic Disorder)
Describe and summarize the below Social Anxiety Disorder: 
Q5  Social Anxiety Disorder

Essential (Required) Features: Marked and excessive fear or anxiety that occurs consistently in one or more social situations such as social interactions (e.g., having a conversation), being observed (e.g., while eating or drinking), or performing in front of others (e.g., giving a speech). The individual is concerned that he or she will act in a way, or show anxiety symptoms, that will be negatively evaluated by others (i.e., be humiliating, embarrassing, lead to rejection, or be offensive). Relevant social situations are consistently avoided or endured with intense fear or anxiety. The symptoms are not transient; that is, they persist for an extended period of time (e.g., at least several months). The symptoms are sufficiently severe to result in significant distress about experiencing persistent anxiety symptoms or result in significant impairment in personal, family, social, educational, occupational, or other important areas of functioning.

Boundaries with Other Disorders and Normality:Social Anxiety Disorder can be differentiated from normal developmental fears (e.g., a child’s reluctance to interact with unfamiliar people in novel situations) by fear and anxiety reactions that are typically excessive, interfere with functioning, and persist over time (e.g., lasting more than several months). (Boundary with normality) Many individuals experience fear in social situations (e.g., it is common for individuals to experience anxiety about public speaking) or manifest the normal personality trait of shyness. Social Anxiety Disorder should only be considered in cases in which the individual reports social fear, anxiety, and avoidance that are clearly in excess of what is normative for the specific cultural context and result in significant distress or impairment. (Boundary with normality). Individuals with certain medical disorders not classified under Mental and Behavioural Disorders (e.g., Parkinson’s Disease) as well as those with other Mental and Behavioural Disorders (e.g., Schizophrenia) may demonstrate avoidance of social situations because of concerns that others will negatively evaluate their symptoms (e.g., tremor, unusual behaviours). An additional diagnosis of Social Anxiety Disorder should only be assigned if all diagnostic requirements are met taking in to consideration that it is normal for individuals with visible symptoms of a medical disorder to experience some concerns about how others perceive their symptoms. Typically, individuals with medical disorders adapt to concerns related to their manifest symptoms and do not display persistent excessive fear or anxiety in social situations. (Boundary with other Mental and Behavioural Disorders or a Disorder or Disease Classified Elsewhere)
 
Fear or anxiety in Agoraphobia centers on imminent perceived dangerous outcomes (e.g., panic attacks, symptoms of panic, incapacitation, or embarrassing physical symptoms) that are anticipated to occur in multiple situations where obtaining help or escaping might be difficult rather than on concerns that others are negatively evaluating them. Unlike Social Anxiety Disorder, embarrassment in Agoraphobia is secondary to the concerns that escape or obtaining assistance may not be possible should symptoms (e.g., diarrhea in a public place) occur. (Boundary with Agoraphobia)
 
Panic Disorder is characterized by recurrent, unexpected, self-limited panic attacks that occur in multiple situations, whereas when panic attacks occur in Social Anxiety Disorder, they are restricted to social situations. However, Panic Disorder and Social Anxiety Disorder are frequently comorbid and if definitional requirements for both disorders are met both can be diagnosed. (Boundary with Panic Disorder)
Describe and summarize the below Social Anxiety Disorder: 
Q5  Social Anxiety Disorder

Essential (Required) Features: Marked and excessive fear or anxiety that occurs consistently in one or more social situations such as social interactions (e.g., having a conversation), being observed (e.g., while eating or drinking), or performing in front of others (e.g., giving a speech). The individual is concerned that he or she will act in a way, or show anxiety symptoms, that will be negatively evaluated by others (i.e., be humiliating, embarrassing, lead to rejection, or be offensive). Relevant social situations are consistently avoided or endured with intense fear or anxiety. The symptoms are not transient; that is, they persist for an extended period of time (e.g., at least several months). The symptoms are sufficiently severe to result in significant distress about experiencing persistent anxiety symptoms or result in significant impairment in personal, family, social, educational, occupational, or other important areas of functioning.

Boundaries with Other Disorders and Normality:Social Anxiety Disorder can be differentiated from normal developmental fears (e.g., a child’s reluctance to interact with unfamiliar people in novel situations) by fear and anxiety reactions that are typically excessive, interfere with functioning, and persist over time (e.g., lasting more than several months). (Boundary with normality) Many individuals experience fear in social situations (e.g., it is common for individuals to experience anxiety about public speaking) or manifest the normal personality trait of shyness. Social Anxiety Disorder should only be considered in cases in which the individual reports social fear, anxiety, and avoidance that are clearly in excess of what is normative for the specific cultural context and result in significant distress or impairment. (Boundary with normality). Individuals with certain medical disorders not classified under Mental and Behavioural Disorders (e.g., Parkinson’s Disease) as well as those with other Mental and Behavioural Disorders (e.g., Schizophrenia) may demonstrate avoidance of social situations because of concerns that others will negatively evaluate their symptoms (e.g., tremor, unusual behaviours). An additional diagnosis of Social Anxiety Disorder should only be assigned if all diagnostic requirements are met taking in to consideration that it is normal for individuals with visible symptoms of a medical disorder to experience some concerns about how others perceive their symptoms. Typically, individuals with medical disorders adapt to concerns related to their manifest symptoms and do not display persistent excessive fear or anxiety in social situations. (Boundary with other Mental and Behavioural Disorders or a Disorder or Disease Classified Elsewhere)
 
Fear or anxiety in Agoraphobia centers on imminent perceived dangerous outcomes (e.g., panic attacks, symptoms of panic, incapacitation, or embarrassing physical symptoms) that are anticipated to occur in multiple situations where obtaining help or escaping might be difficult rather than on concerns that others are negatively evaluating them. Unlike Social Anxiety Disorder, embarrassment in Agoraphobia is secondary to the concerns that escape or obtaining assistance may not be possible should symptoms (e.g., diarrhea in a public place) occur. (Boundary with Agoraphobia)
 
Panic Disorder is characterized by recurrent, unexpected, self-limited panic attacks that occur in multiple situations, whereas when panic attacks occur in Social Anxiety Disorder, they are restricted to social situations. However, Panic Disorder and Social Anxiety Disorder are frequently comorbid and if definitional requirements for both disorders are met both can be diagnosed. (Boundary with Panic Disorder)
Describe and summarize the below Social Anxiety Disorder: 
Q5  Social Anxiety Disorder

Essential (Required) Features: Marked and excessive fear or anxiety that occurs consistently in one or more social situations such as social interactions (e.g., having a conversation), being observed (e.g., while eating or drinking), or performing in front of others (e.g., giving a speech). The individual is concerned that he or she will act in a way, or show anxiety symptoms, that will be negatively evaluated by others (i.e., be humiliating, embarrassing, lead to rejection, or be offensive). Relevant social situations are consistently avoided or endured with intense fear or anxiety. The symptoms are not transient; that is, they persist for an extended period of time (e.g., at least several months). The symptoms are sufficiently severe to result in significant distress about experiencing persistent anxiety symptoms or result in significant impairment in personal, family, social, educational, occupational, or other important areas of functioning.

Boundaries with Other Disorders and Normality:Social Anxiety Disorder can be differentiated from normal developmental fears (e.g., a child’s reluctance to interact with unfamiliar people in novel situations) by fear and anxiety reactions that are typically excessive, interfere with functioning, and persist over time (e.g., lasting more than several months). (Boundary with normality) Many individuals experience fear in social situations (e.g., it is common for individuals to experience anxiety about public speaking) or manifest the normal personality trait of shyness. Social Anxiety Disorder should only be considered in cases in which the individual reports social fear, anxiety, and avoidance that are clearly in excess of what is normative for the specific cultural context and result in significant distress or impairment. (Boundary with normality). Individuals with certain medical disorders not classified under Mental and Behavioural Disorders (e.g., Parkinson’s Disease) as well as those with other Mental and Behavioural Disorders (e.g., Schizophrenia) may demonstrate avoidance of social situations because of concerns that others will negatively evaluate their symptoms (e.g., tremor, unusual behaviours). An additional diagnosis of Social Anxiety Disorder should only be assigned if all diagnostic requirements are met taking in to consideration that it is normal for individuals with visible symptoms of a medical disorder to experience some concerns about how others perceive their symptoms. Typically, individuals with medical disorders adapt to concerns related to their manifest symptoms and do not display persistent excessive fear or anxiety in social situations. (Boundary with other Mental and Behavioural Disorders or a Disorder or Disease Classified Elsewhere)
 
Fear or anxiety in Agoraphobia centers on imminent perceived dangerous outcomes (e.g., panic attacks, symptoms of panic, incapacitation, or embarrassing physical symptoms) that are anticipated to occur in multiple situations where obtaining help or escaping might be difficult rather than on concerns that others are negatively evaluating them. Unlike Social Anxiety Disorder, embarrassment in Agoraphobia is secondary to the concerns that escape or obtaining assistance may not be possible should symptoms (e.g., diarrhea in a public place) occur. (Boundary with Agoraphobia)
 
Panic Disorder is characterized by recurrent, unexpected, self-limited panic attacks that occur in multiple situations, whereas when panic attacks occur in Social Anxiety Disorder, they are restricted to social situations. However, Panic Disorder and Social Anxiety Disorder are frequently comorbid and if definitional requirements for both disorders are met both can be diagnosed. (Boundary with Panic Disorder)
 
Specific Phobia can be differentiated from Social Anxiety Disorder because, in general, fears are of specific situations or stimuli (e.g., heights, animals, blood-injury) that are not social contexts. (Boundary with Specific Phobia)
 
Generalized Anxiety Disorder can be differentiated from Social Anxiety Disorder because the main focus is worry about negative consequences that can occur in multiple everyday situations (e.g., work, relationships, finances) rather than being restricted to concerns about one’s behaviour or appearance being negatively evaluated in social situations. (Boundary with Generalized Anxiety Disorder)
 
Selective Mutism is characterized by a failure to speak in specific situations whereas in Social Anxiety Disorder fear and anxiety result in avoidance of multiple social contexts. If definitional requirements of both disorders are met, both can be diagnosed. (Boundary with Selective Mutism)
 
Beliefs of social inadequacy, rejection, and failure are common in Depressive Disorders and may be associated with avoidance of social situations. However, unlike in Social Anxiety Disorder, these symptoms occur almost exclusively during a Depressive Episode. (Boundary with Depressive Disorders)

Additional Features: Individuals with Social Anxiety Disorder may report concerns about physical symptoms, such as blushing, sweating, or trembling rather than initially endorsing fears of negative evaluation. Social Anxiety Disorder is highly comorbid with other Anxiety Disorders as well as Depressive Disorders. Individuals with Social Phobia are at higher risk for developing Substance Use Disorders, which may arise subsequent to use for the purposes of attenuating anxiety symptoms in social situations. Individuals may not view their fear or anxiety in response to social situations as excessive. As such, clinical judgment should be applied to determine whether the reported fear, anxiety, and/or avoidance behaviour is disproportionate to what the social situation warrants taking into consideration both accepted cultural norms as well as the specific environmental conditions that the individual is normally subjected to (e.g., fear of interacting with peers may be appropriate if the individual is being bullied).

\n[/INST]\n\n   
"""
device = torch.device("cuda")
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
input_ids = input_ids.to(device)
torch.manual_seed(60)

generation_output = model.generate(
    input_ids=input_ids,
    max_new_tokens=1024,
    num_beams=1,
    last_context_length=1792,
    do_sample=True,
    temperature=0.3,
    streamer=streamer,
)

print(tokenizer.decode(generation_output[0]))

